server:
  port: 9527

fall:
  gateway:
    service:
      name: fall-gateway-
      version: payn

spring:
  application:
    name: fall-gateway
  cloud:
    config:
      override-none: true
    nacos:
      discovery:
        server-addr: 127.0.0.1
        namespace: platform-dev
        group: DEFAULT_GROUP
        service: ${fall.gateway.service.name}${fall.gateway.service.version}
        ip: 127.0.0.1       #用于指定注册地址127.0.0.1
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: platform-console-control-payn  # 路由ID,没有固定的规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://platform-console-control-payn
          predicates:
            - Path=/**  # 断言，路径相匹配的进行路由
            - Host=localhost:**
